[tool.poetry]
name = "tap-npm"
version = "0.0.1"
description = "`tap-npm` is a Singer tap for NPM, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramírez-Mondragón"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.10,>=3.6.1"
requests = "^2.25.1"
singer-sdk = "^0.3.10"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-npm = 'tap_npm.tap:TapNPM.cli'
