[tool.poetry]
name = "tap-npm"
version = "0.0.1"
description = "`tap-npm` is a Singer tap for NPM, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramírez-Mondragón"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.11,>=3.7.1"
singer-sdk = "==0.9.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = {version = "^22.6", allow-prereleases = true}
isort = "^5.9.3"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_npm"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-npm = 'tap_npm.tap:TapNPM.cli'
